name: 'Amazon Inspector SBOM Generator'
description: 'Generate SBOMs and scan for vulnerabilities in your project repository or build artifacts'
inputs:
  artifact:
    description: 'TBD'
    required: true
    default: 'repository'
outputs:
  TBD:
    description: 'TBD'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifact }}

