name: 'Amazon Inspector SBOM Generator'
description: 'Generate SBOMs and scan for vulnerabilities in your project repository or build artifacts'
inputs:
  artifact:
    description: 'The artifact you would like to scan with Amazon Inspector. Valid choices are "repository", "container", "binary", or "archive".'
    required: true
    default: 'repository'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifact }}

