name: 'Amazon Inspector SBOM Generator'
description: 'Generate SBOMs and scan for vulnerabilities in your project repository or build artifacts'

inputs:
  artifact_type:
    description: 'The artifact you would like to scan with Amazon Inspector. Valid choices are "repository", "container", "binary", or "archive".'
    required: true
    default: 'repository'

  artifact_path:
    description: 'The path to the artifact you would like to scan with Amazon Inspector. If scanning a container image, you must provide a  value that follows the docker pull convention: "NAME[:TAG|@DIGEST]", for example, "alpine:latest", or a path to an image exported as tarball using "docker save".'
    required: yes
    default: './'

  output_sbom_path:
    description: 'TBD' 
    required: yes
    default: '/tmp/sbom.json'

  output_inspector_scan_path:
    description: 'TBD' 
    required: yes
    default: '/tmp/inspector_scan.json'


  enable_vulnerability_thresholds:
    description: 'If set to true, this will cause the Action to fail with exit code 1 if vulnerability thresholds are exceeded. This is intended to block uploads of build artifacts when the vulnerability threshold is exceeded.'
    required: no
    default: false

  critical_threshold:
    description: "tbd"
    required: no
    default: 0

  high_threshold:
    description: "tbd"
    required: no
    default: 0

  medium_threshold:
    description: "tbd"
    required: no
    default: 0

  low_threshold:
    description: "tbd"
    required: no
    default: 0

outputs:
  sbom:
    description: 'tbd'
    value: 'foo'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifact_type }}
    - ${{ inputs.artifact_path }}
    - ${{ inputs.output_sbom_path }}
    - ${{ inputs.output_inspector_scan_path }}
    - ${{ inputs.enable_vulnerability_thresholds }}
    - ${{ inputs.critical_threshold }}
    - ${{ inputs.high_threshold }}
    - ${{ inputs.medium_threshold }}
    - ${{ inputs.low_threshold }}


