name: 'Amazon Inspector SBOM Generator'
description: 'Generate SBOMs and scan for vulnerabilities in your project repository or build artifacts such as container images, archives, or compiled Go or Rust binaries.'

inputs:
  artifact_type:
    description: 'The artifact type you would like to scan with Amazon Inspector. Valid choices are "repository", "container", "binary", or "archive".'
    required: yes
    default: 'repository'

  artifact_path:
    description: 'The filepath to the artifact you would like to scan with Amazon Inspector. If scanning a container image, you must provide a value that follows the docker pull convention: "NAME[:TAG|@DIGEST]", for example, "alpine:latest", or a filepath to an image exported as tarball using "docker save".'
    required: yes
    default: './'

  enable_vulnerability_thresholds:
    description: 'If set to true, this will cause the Action to fail with exit code 1 when vulnerability thresholds are exceeded. This is intended to block uploads of build artifacts when the vulnerability threshold is exceeded.'
    required: no
    default: false

  critical_threshold:
    description: "The number of critical vulnerabilities that should trigger Action failure; this value does nothing when set to zero."
    required: no
    default: 0

  high_threshold:
   description: "The number of high vulnerabilities that should trigger Action failure; this value does nothing when set to zero."
    required: no
    default: 0

  medium_threshold:
    description: "The number of medium vulnerabilities that should trigger Action failure; this value does nothing when set to zero."
    required: no
    default: 0

  low_threshold:
    description: "The number of low vulnerabilities that should trigger Action failure; this value does nothing when set to zero."
    required: no
    default: 0


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifact_type }}
    - ${{ inputs.artifact_path }}
    - ${{ inputs.enable_vulnerability_thresholds }}
    - ${{ inputs.critical_threshold }}
    - ${{ inputs.high_threshold }}
    - ${{ inputs.medium_threshold }}
    - ${{ inputs.low_threshold }}

