name: 'Amazon Inspector SBOM Generator'
description: 'Generate SBOMs and scan for vulnerabilities in your project repository or build artifacts'

inputs:
  artifact_type:
    description: 'The artifact you would like to scan with Amazon Inspector. Valid choices are "repository", "container", "binary", or "archive".'
    required: True
    default: 'repository'

  artifact_path:
    description: 'The path to the artifact you would like to scan with Amazon Inspector. If scanning a container image, you must provide a value that follows the docker pull convention: "NAME[:TAG|@DIGEST]", for example, "alpine:latest", or a path to an image exported as tarball using "docker save".'
    required: True
    default: './'

  output_sbom_path:
    description: "The destination file path for the generated SBOM."
    required: False
    default: '/tmp/sbom.json'

  output_inspector_scan_path:
    description: "The destination file path for Inspector's vulnerability scan (JSON format)."
    required: False
    default: '/tmp/inspector_scan.json'

  output_inspector_scan_path_csv:
    description: "The destination file path for Inspector's vulnerability scan (CSV format)."
    required: False
    default: '/tmp/inspector_scan.csv'


  sbomgen_version:
    description: "The inspector-sbomgen version you wish to use for SBOM generation. See here for more info: https://docs.aws.amazon.com/inspector/latest/user/sbom-generator.html"
    required: False
    default: "latest"


  critical_threshold:
    description: "Specifies the number of critical vulnerabilities to trigger job failure."
    required: False
    default: 0

  high_threshold:
    description: "Specifies the number of high vulnerabilities to trigger job failure."
    required: False
    default: 0

  medium_threshold:
    description: "Specifies the number of medium vulnerabilities to trigger job failure."
    required: False
    default: 0

  low_threshold:
    description: "Specifies the number of low vulnerabilities to trigger job failure."
    required: False
    default: 0

  other_threshold:
    description: "Specifies the number of 'other' vulnerabilities to trigger job failure, such as 'info', 'none', or 'unknown'."
    required: False
    default: 0

  scanners:
    description: "Specifies the file scanners that you would like inspector-sbomgen to execute. By default, inspector-sbomgen will try to run all file scanners that are applicable to the target artifact. If this argument is set, inspector-sbomgen will only execute the specified file scanners. Provide your input as a single string. Separate each file scanner with a comma. To view a list of available file scanners, execute 'inspector-sbomgen list-scanners'. See here for more info: https://docs.aws.amazon.com/inspector/latest/user/sbom-generator.html"
    required: False
    default: "''"
    # Example:
    #  scanners: dpkg,python-requirements,javascript-nodejs

  skip_scanners:
    description: "Specifies a list of file scanners that should NOT be executed; this argument cannot be combined with 'scanners'. If this argument is set, inspector-sbomgen will execute all file scanners except those you specified. Provide your input as a single string. Separate each file scanner with a comma. To view a list of available file scanners, execute 'inspector-sbomgen list-scanners'. See here for more info: https://docs.aws.amazon.com/inspector/latest/user/sbom-generator.html"
    required: False
    default: "''"
    # Example:
    #   skip_scanners: 'binaries,alpine-apk,dpkg,php'

  skip_files:
    description: "Specifies one or more files and/or directories that should NOT be inventoried. Separate each file with a comma and enclose the entire string in double quotes."
    required: False
    default: "''"
    # Example:
    #   skip_files: "./media,/tmp/foo/,/bar/my_program"

outputs:
  artifact_sbom:
    description: "The filepath to the artifact SBOM."

  inspector_scan_results:
    description: "The filepath to the Inspector vulnerability scan in JSON format."

  inspector_scan_results_csv:
    description: "The filepath to the Inspector vulnerability scan in CSV format."

  vulnerability_threshold_exceeded:
    description: "This variable is set to 1 if any vulnerability threshold was exceeded, otherwise it is 0."

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - --artifact-type=${{ inputs.artifact_type }}
    - --artifact-path=${{ inputs.artifact_path }}
    - --out-sbom=${{ inputs.output_sbom_path}}
    - --out-scan=${{ inputs.output_inspector_scan_path }}
    - --out-scan-csv=${{ inputs.output_inspector_scan_path_csv }}
    - --sbomgen-version=${{ inputs.sbomgen_version }}
    - --thresholds
    - --critical=${{ inputs.critical_threshold }}
    - --high=${{ inputs.high_threshold }}
    - --medium=${{ inputs.medium_threshold }}
    - --low=${{ inputs.low_threshold }}
    - --other=${{ inputs.other_threshold }}
    - --scanners=${{ inputs.scanners }}
    - --skip-scanners=${{ inputs.skip_scanners }}
    - --skip-files=${{ inputs.skip_files }}
