on: [push]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    environment:
      name: plugin-development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: app:latest
          load: true

      - name: check local images
        run: docker images

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Scan artifact with Inspector
        uses: ./ # Uses an action in the root directory
        id: inspector
        with:
          artifact_type: 'container'
          artifact_path: 'app:latest'
          output_sbom_path: 'sbom.json'
          output_inspector_scan_path: 'inspector_scan.json'
          output_inspector_scan_path_csv: 'inspector_scan.csv'
          critical_threshold: 1
          high_threshold: 1
          medium_threshold: 1
          low_threshold: 1
          other_threshold: 1

      - name: Demonstrate SBOM Output (JSON)
        run: cat ${{ steps.inspector.outputs.artifact_sbom }}
 
      - name: Demonstrate Inspector Scan Output (JSON)
        run: cat ${{ steps.inspector.outputs.inspector_scan_results }}

      - name: Demonstrate Inspector Scan Output (CSV)
        run: cat ${{ steps.inspector.outputs.inspector_scan_results_csv }}

      - name: Upload Inspector Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: Inspector Scan SBOM Results
          path: |
            ${{ steps.inspector.outputs.inspector_scan_results }}
            ${{ steps.inspector.outputs.inspector_scan_results_csv }}
            ${{ steps.inspector.outputs.artifact_sbom }}

      - name: Post Job Summary
        run: |
          echo "# Amazon Inspector Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo ":rotating_light: NOTE: THIS IS A MOCKUP" >> $GITHUB_STEP_SUMMARY
          echo "Artifact Name: *alpine:edge*" >> $GITHUB_STEP_SUMMARY
          echo "Artifact Type: *container*" >> $GITHUB_STEP_SUMMARY
          echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Critical | 5     |" >> $GITHUB_STEP_SUMMARY
          echo "| High     | 10    |" >> $GITHUB_STEP_SUMMARY
          echo "| Medium   | 15    |" >> $GITHUB_STEP_SUMMARY
          echo "| Low      | 20    |" >> $GITHUB_STEP_SUMMARY
          echo "| Other    | 0     |" >> $GITHUB_STEP_SUMMARY

      - name: Fail if vulnerability threshold is exceeded
        run: exit ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}

      - name: Upload image to registry
        run: echo docker push
