on: [push]

jobs:
  inspector:
    runs-on: ubuntu-latest
    name: "Amazon Inspector Scan"
    environment:
      name: plugin-development
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Scan image with Amazon Inspector
        uses: ./ 
        id: inspector
        with:
          artifact_type: 'container'
          artifact_path: 'ubuntu:14.04'

      - name: Upload Inspector Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: Inspector Scan SBOM Results
          path: |
            ${{ steps.inspector.outputs.artifact_sbom }}
            ${{ steps.inspector.outputs.inspector_scan_results }}
            ${{ steps.inspector.outputs.inspector_scan_results_csv }}

    - name: Post Job Summary
      run: echo "test"
