name: Semgrep Scan

on: [push]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

        - name: full scan
          run: |
            semgrep \
              --sarif --output report.sarif \
              --metrics=off \
              --config="p/default"
        
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@v4.3.2
          with:
            name: report.sarif
            path: report.sarif
            
        - name: Download report
          uses: actions/download-artifact@v4.1.5
          with: 
            name: report.sarif
