name: Scan for Secrets

# This workflow tests that the action can successfully
# scan a GitHub repository. This workflow runs automatically
# every 6 hours, and on pushes.

on: [push]

jobs:
  daily_job:
    runs-on: ubuntu-latest
    environment:
      name: plugin-development

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.73.0
        with:
          extra_args: --only-verified
            


