name: Test Container Use Case

# This workflow tests that the action can successfully
# scan a GitHub repository. This workflow runs automatically
# every 6 hours, and on pushes.

on:
  schedule:
    - cron: '0 */6 * * *' # runs every 6 hours
  push:
    branches: #
      - '*'

jobs:
  daily_job:
    runs-on: ubuntu-latest
    environment:
      name: plugin-development

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # TODO: use an IAM role

      - name: Test Repository Scan
        uses: aws/amazon-inspector-github-actions-plugin@main 
        # TODO: update this to point to public v1.0.0 release
        with:
          artifact_type: 'container'
          artifact_path: 'ubuntu:14.04'

      # TODO: read the repository results and validate correctness

      # only run if the previous step failed
      - name: Notify maintainers of validation failure 
        if: ${{ failure() }}
        run: echo "this feature is not implemented"
        # TODO: add steps to send notification to a Lambda to cut a ticket on job failure

