name: Test Action Installation

on:
  schedule:
    - cron: '0 10 * * *' # every day at 10:00 AM EST
  pull_request:
    paths-ignore:
      - '**/README.md'

jobs:
  daily_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: foo
        run: cat README.md

  pull_request_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: foo
        run: cat README.md


